version: '3.4'

networks:
  dotnetcorenetwork:

volumes:
    grafana_data: {}

services:
  aspnetcore:
    image: mattklup/aspnetcore-5:1.0
    ports:
      - 8080:80
    networks:
      - dotnetcorenetwork

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    depends_on:
      - aspnetcore
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorenetwork

  grafana:
      image : grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      restart: always
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=ChangeThis!
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      networks:
        - dotnetcorenetwork

  fluent-bit:
    image: fluent/fluent-bit
    depends_on:
      - elasticsearch
    volumes:
      - ./fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf

    networks:
      - dotnetcorenetwork

  elasticsearch:
    image: elasticsearch:7.6.2
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
    networks:
      - dotnetcorenetwork
