version: '3.4'

networks:
  dotnetcorenetwork:

volumes:
    grafana_data:
    logger_data:
    db_data:

services:

  aspnetcore-1:
    image: mattklup/aspnetcore-5:local
    ports:
      - 8081:80
    environment:
      DB_CONNECTION_STRING: tbd
    networks:
      - dotnetcorenetwork

  aspnetcore-2:
    image: mattklup/aspnetcore-5:local
    ports:
      - 8082:80
    environment:
      DB_CONNECTION_STRING: tbd
    networks:
      - dotnetcorenetwork

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    depends_on:
      - aspnetcore
    ports:
      - 9090:9090
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorenetwork

  grafana:
      image : grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      restart: always
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=ChangeThis!
        - GF_USERS_ALLOW_SIGN_UP=false
      volumes:
        - grafana_data:/var/lib/grafana
        - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
        - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      networks:
        - dotnetcorenetwork

  jaeger:
    image: jaegertracing/opentelemetry-all-in-one
    ports:
      - 13133:13133 # health check
      - 16686:16686 # dashboard
      - 4317:55680 # OTLP
    networks:
      - dotnetcorenetwork
