version: '3.4'

networks:
  dotnetcorenetwork:

services:
  web:
    image: mattklup/aspnetcore-5:1.0
    ports:
      - 8080:80
    networks:
      - dotnetcorenetwork

  prometheus:
    image: quay.io/prometheus/prometheus:latest
    depends_on:
      - web
    ports:
      - 9090:9090
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - dotnetcorenetwork

  grafana:
      image : grafana/grafana
      depends_on:
        - prometheus
      ports:
        - 3000:3000
      restart: always
      environment:
        - GF_SECURITY_ADMIN_PASSWORD=ChangeThis!
        - GF_USERS_ALLOW_SIGN_UP=false
      networks:
        - dotnetcorenetwork
