version: '3.4'

services:

  fortio:
    image: fortio/fortio
    command: load -c 32 -qps 25 -t 2m http://aspnetcore-1/loadtest
    depends_on:
      - aspnetcore-1
      - aspnetcore-2
      - aspnetcorebackend-1
    ports:
      - 8079:8079
      - 8080:8080
    networks:
      - dotnetcorenetwork
