scrape_configs:
  - job_name: aspnetcore-prometheus
    scrape_interval: 15s
    scrape_timeout: 10s
    scheme: http
    metrics_path: /metrics
    static_configs:
    - targets:
      - aspnetcore:80
