name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Docker Login
      env:
        DOCKER_USER: ${{secrets.DOCKER_HUB_USERNAME}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_HUB_ACCESS_TOKEN}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag ${{secrets.DOCKER_HUB_USERNAME}}/aspnetcore-5:2 #${GITHUB_RUN_NUMBER}

    - name: Push the Docker image
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/aspnetcore-5:2 #${GITHUB_RUN_NUMBER}
